// Tolong Hargain yang udah buat story ya..


export const stories = {
    pengenalantokoh: `Latar Belakang Cerita:
    Kerajaan yang damai di mana keluarga Aubert tinggal tiba-tiba terancam oleh kekuatan jahat yang ingin menguasai dunia. Saat itu, keluarga Aubert menjadi satu-satunya harapan untuk menghadapi ancaman tersebut. Setiap anggota keluarga Aubert harus menggunakan kekuatan magis mereka dan bekerja sama untuk menyelamatkan kerajaan dan mencegah kehancuran.
    Dalam perjalanan mereka, keluarga Aubert menghadapi berbagai tantangan dan mengungkap rahasia keluarga mereka sendiri. Mereka belajar tentang sejarah panjang keluarga mereka dan peran mereka dalam menjaga keseimbangan kekuatan di dunia.
    Karakter Utama:
    1. Lucas Aubert: Lucas adalah sosok yang tangguh dan penuh keberanian. Ia memiliki kemampuan mengendalikan elemen api dan memiliki kepribadian yang penuh semangat. Lucas selalu berusaha melindungi keluarganya dan menjadi pemimpin alami di antara saudara-saudaranya.
    2. Amelia Aubert: Amelia adalah karakter yang berbakat dalam seni sihir dan memiliki kekuatan mengendalikan elemen angin. Ia memiliki kepribadian yang riang dan ceria, namun di balik itu ia memiliki rasa tanggung jawab yang besar terhadap keluarganya.
    3. Louis Aubert: Louis adalah ahli strategi yang ulung. Ia memiliki keahlian taktik dan pengetahuan yang luas tentang sejarah dan mitologi. 
    4. Adeline Aubert: Adeline adalah karakter yang cerdas dan berwawasan luas. Ia memiliki kekuatan magis dalam mengendalikan air dan memiliki kepekaan terhadap emosi orang lain. 
    5. Auguste Aubert: Auguste adalah karakter yang kuat dan memiliki kekuatan fisik yang luar biasa. Ia dapat mengendalikan kekuatan listrik dan memiliki naluri pejuang yang kuat. Meskipun terlihat kasar, 
    6. Clara Aubert: Clara adalah karakter dengan kemampuan penyembuhan yang luar biasa. Ia mampu menggunakan kekuatan penyembuhan dan memulihkan energi orang lain. 
    7. Clayza Aubert: Clayza adalah karakter misterius yang memiliki kemampuan untuk berkomunikasi dengan makhluk-makhluk gaib. Ia memiliki kekuatan magis dalam mengendalikan bayangan dan kegelapan. 
    `,
    prolog: `Kerajaan yang damai di mana keluarga Aubert tinggal tiba-tiba terancam oleh kekuatan jahat yang ingin menguasai dunia. Saat itu, keluarga Aubert menjadi satu-satunya harapan untuk menghadapi ancaman tersebut. Setiap anggota keluarga Aubert harus menggunakan kekuatan magis mereka dan bekerja sama untuk menyelamatkan kerajaan dan mencegah kehancuran.
    Dalam perjalanan mereka, keluarga Aubert menghadapi berbagai tantangan dan mengungkap rahasia keluarga mereka sendiri. Mereka belajar tentang sejarah panjang keluarga mereka dan peran mereka dalam menjaga keseimbangan kekuatan di dunia.
    `,
    story1: `Season 1: Rise of the Aubert Family

    Di dunia yang penuh dengan keajaiban dan bahaya, ada sebuah keluarga bangsawan yang terkenal, keluarga Aubert. Keluarga ini terdiri dari tujuh bersaudara, yaitu Lucas Aubert, Amelia Aubert, Louis Aubert, Adeline Aubert, Auguste Aubert, Clara Aubert, dan Clayza Aubert. Setiap anggota keluarga Aubert memiliki kekuatan dan bakat yang berbeda. 
    Namun, di balik kehidupan mereka yang berbahagia, ada kekuatan kegelapan yang mengerikan yang mulai mengancam dunia. Raja Kegelapan yang kuat bernama Malgarius ingin menguasai dunia dan menghancurkan segala kehidupan yang ada. Dia berambisi untuk mencari keabadian dan kekuasaan mutlak.
    `,
    story2: `Sebelum serangan Malgarius, orang tua mereka, Hendrith Aubert dan Isabelle Aubert, memimpin sebuah ekspedisi ke dalam Tanah Kehancuran, sebuah wilayah yang dikenal sebagai pusat kekuatan gelap. Tujuan ekspedisi ini adalah untuk menyelidiki tanda-tanda ancaman yang muncul dan memahami rencana sebenarnya Malgarius.
    Namun, dalam ekspedisi tersebut, sesuatu yang mengerikan terjadi. Mereka tiba-tiba berhadapan dengan pasukan kegelapan yang mengunakan artefak dan terperangkap di dalam wilayah gelap yang tak terduga. Hendrith Aubert dan Isabelle Aubert berjuang mati-matian untuk melindungi anggota ekspedisi mereka, sebagian anggota ekspedisi tidak berhasil di selamatkan dan sebagiannya berhasil kembali ke istana kerajaan dengan selamat tetapi di dalam kekacauan tersebut, Orang tua aubert menghilang secara misterius. Tidak ada yang tahu apakah mereka telah meninggal atau diculik oleh kekuatan gelap.
    `,
    story3: `Ketika para anggota keluarga Aubert mengetahui kepergian orang tua mereka, amarah dan kesedihan menyelimuti hati mereka. Mereka merasa terkhianati oleh orang tua mereka yang telah mengambil risiko besar tanpa memberitahu mereka sebelumnya. Kehilangan orang tua mereka memunculkan dendam dan motivasi baru bagi saudara-saudara Aubert untuk melawan Malgarius dengan segala yang mereka miliki. Lucas Aubert mengambil alih kepemimpinan keluarga. Perintah pertamanya untuk ke 6 saudaranya agar mengingkatkat kekuatan mereka untuk melakukan pembalasan dendam.`,
    story4: `8 bulan telah berlalu... Saat  Di mana Malgarius dan pasukannya menyerang kerajaan Alexandria, keluarga Aubert bersatu untuk melawan ancaman ini serta membalaskan dendam  untuk kedua orang tuanya. Dalam pertempuran sengit, mereka berhasil menghadapi pasukan Kegelapan, tetapi Malgarius yang di persenjatai dengan artefak kuno sangatlah kuat, sangat sulit untuk menghabisinya saat itu juga, Clayza yang teringat sebuah mantra kuno yang dapat menyegel individu ke dunia lain mantra itu di beritahu oleh ibunya tetapi saat itu ibunya tidak menyelesaikan bembicaraan itu tentang apa sebab dan akibatnya, dan akhirnya berhasil mengalahkan Raja Kegelapan dalam pertarungan epik. Namun, kemenangan ini datang dengan harga yang sangat besar.`,
    story5: `Dalam upaya terakhir untuk menyelamatkan dunia, Clayza mengunakan mantra kuno yang kuat untuk mengunci Malgarius dalam dimensi lain, seluruh saudaranya melingdungi Clayza agar dapat mengunakan mantra kuno itu. Ketika mantra kuno sudah berhasil di gunakan kalung pemberian ibunya yang di berikan ke Clayza bersinar terang, tetapi perbuatan itu mengorbankan ke 6 saudaranya. Setiap anggota keluarga Aubert, kecuali Clayza, harus tidur dalam keabadian untuk selamanya.
    Clayza Aubert, yang selamat dari perang itu, menjadi satu-satunya yang tersisa dari keluarga bangsawan ini. Di saat kekuantanya sudah mencapai batasnya dia merasa sangat sedih dan sangat menyesal atas apa yang dia lakukan, tindaknya menyebabkan saudara saudarnya menerima imbasnya, tak butuh waktu lama Clayza bertekad untuk membangunkan mereka kembali. Sebagai seorang penyihir yang mahir, Clayza tahu bahwa satu-satunya cara untuk memecahkan kutukan itu adalah dengan mengumpulkan kekuatan yang luar biasa.
    `,
    story6: `Season 2: The Awakening of the Auberts

    Season kedua dimulai dengan Clayza yang telah mengembara di seluruh dunia selama bertahun-tahun untuk mencari cara untuk membangunkan saudara-saudaranya dari tidur abadi mereka. Dia menghadapi berbagai macam bahaya, menemukan sekutu baru, dan memperkuat kekuatannya.
    Dalam pencariannya, Clayza menemukan buku kuno yang berisi rahasia kekuatan magis luar biasa. Dalam buku itu, tertulis tentang "Bunga Keabadian," bunga yang dikatakan dapat memecahkan kutukan dan membangunkan orang-orang yang tidur dalam keabadian. Namun, bunga itu hanya dapat ditemukan di daerah terpencil yang sangat berbahaya.
    `,
    story7: `Clayza memutuskan untuk mengambil risiko dan pergi mencari Bunga Keabadian. Dalam perjalanannya, dia bertemu dengan berbagai orang dan penjahat, serta menghadapi makhluk-makhluk yang belum pernah dia kenali dan pengikut Malgarius yang tersisa. Dia berjuang melawan mereka dengan menggunakan kekuatan sihirnya dan pengalaman yang dia peroleh.
    Waktu terus berjalan Sudah 5 tahun berlalu semenjak Clayza Pergih untuk mencari keberadaan bunga kehidupan, Semakin dalam dia mencari keberadaan bunga kehidupan, semakin banyak juga teka teki yang dia temukan, sudah tidak terhitung berapa reruntuhan yang sudah dia jelajahi untuk mencari keberadaan bunga keabadian, tetapi bukanya menemukan petunjuk selanjutnya tentang bunga keabadian dia malah menemukan petunjuk tentang kedua orangtuanya yang dinyatakan menghilang ketika expedisi, dia menemukan catatan dan barang milik ibunya, catatan itu berisi “Waktu akan memberikan jawaban, tetaplah berjalan di jalan  yang kamu percayai. Emosi, tanggung jawab, kesedihan, kesepian, raasa bersalah. Jangan biarkan mereka mengalahkan dirimu, percayalah seberapa berat beban yang kamu pikul yakinlah bahwa kamu bisa melewati itu semua, Maaf kami belum bisa menemuimu, kami masih memiliki sesuatu hal yang sangat penting yang harus kami lakukan... Tetaplah berjalan keutara.” 
    `,
    story8: `Clayza yang membaca itu merasa bersyukur karna kedua orang tuanya masih hidup, air mata terus keluar dan dia tak berhenti menangis, saat itu juga clayza merasakan bahwa perkiraanya benar tentang kedua orangtuanya yang masih hidup dan tentang mamanya yang mengetahui beban yang dia pikul, Di saat itu pula Clayza berfikir “Aku pasti bisa mengakhiri semua ini, jika mama yang bisa melihat kilas masa depan sudah berkata seperti itu maka aku hanya harus membuat itu menjadi kenyataan, yaa walau ada pertanyaan tentang kenapa mama memberikan kalung ini kepadaku... Hah...sudah lah aku akan tanyakan pada mama ketika sudah bertemu denganya kembali. Untuk sekarang mari fokus untuk membangunkan saudara saudaraku terlebih dahulu, Mari Menuju Utara”, Akhirnya Clayza terus menuju ke utara, tetapi di dalam perjalanan ini, Clayza juga menemukan bahwa kegelapan tidaklah sepenuhnya dikalahkan, dan bahwa ada kekuatan baru yang muncul di balik layar yang ingin menghidupkan kembali Raja Kegelapan. `,
    story9: `Mengikuti Petunjuk yang di berikan orang tuanya, tibalah dia di suatu reruntuhan, seperti biasanya Clayza Masuk ke dalam reruntuhan itu dan melawan monster-monster jenis baru yang belum pernah dia temui, tetapi kali ini berbeda monster disini sangatlah kuat, dan akhirnya Clayza memilih untuk mundur sejenak untuk memulihkan dirinya... “ Aku yakin disinilah letak bunga kehidupan berada, tapi bagaimana caranya masuk lebih dalam jika monster di awal saja sudah membuatku kewalahan seperti ini.” Akhirnya clayza berhasil menembus monster-monster itu dan masuk lebih dalam, membutuhkan waktu 2 tahun untuk dia bisa masuk lebih dalam ke reruntuhan itu, hingga tersisa 1 pintu lagi, dia akhirnya masuk ke dalam untuk melawan monster yang terakhir, dan clayza terkejut bahwa monster terakhir yang akan dia hadapi adalah monster legendaris yang pernah dia dengar di dalam buku sejarah kuno, monster itu adalah Nine Head Dragon, “Naga berkepala 9... Mustahil...Mahluk seperti itu masih ada di dunia ini..., tenanglah tenang... dia adalah last bos, Jadi mari kita serang habis habisan...”`,
    story10: `Clayza pun menyerang monster itu tanpa ragu... 7 hari 7 malam pertarungan yang sangat sengit berjalan selama itu, Hingga di hari ke delapan Nine Head Dragon Berhasil di kalahkan, ketika Nine Head Dragon sudah tak berdaya dan Clayza juga sudah tidak dapat bergerak lagi.. suara Nine head dragon muncul di kepalanya yang bersura “Senang bertemu dengan mu Wahai penghianat kegelapan, Ku Harap Pengetahuan Ini Dapat Membantumu Perjalananmu” Clayza Yang mendegar itu seketika lagsung pingsan selama 3 hari.`,
    story11: `Ketika Clayza bangun dia menyedari ada yang berbeda dengan dirinya, tetapi dia tidak ingin memikirkan itu terlebih dahulu, dan akhirnya bunga kehidupan yang di cari selama 7 tahun lamanya akhirnya ketemu, Clayza mengambil bunga itu dan langsung kembali ke Kardinal Milik Aubert , Namun, dia menyadari bahwa membangunkan saudara-saudaranya bukanlah hal yang mudah. Ritual yang rumit dan risiko yang besar menunggunya. Tetapi dia sama sekali tidak tahu bagaimana menjalankan Ritual itu, Seketika kepala terisi dengan informasi mengenai ritual itu, dan akhirnya clayza menyadari bahwa Nine Head Dragon memberikan pengatahuannya kepadanya, Dan warna rambutnya yang berubah dari hitam menjadi hitam keunguan..

    Season 2 berakhir dengan cliffhanger saat Clayza berdiri di depan tidur abadi saudara-saudaranya, memegang Bunga Keabadian dengan penuh harap. Apakah dia berhasil membangunkan saudara-saudaranya? 
    `,
    story12: `Season 3: The Rebirth of Aubert Legacy

    Season ketiga dimulai dengan momen yang sangat ditunggu-tunggu: Clayza yang memegang Bunga Keabadian dengan harapan besar untuk membangunkan saudara-saudaranya. Dengan hati berdebar, dia meletakkan bunga itu di dekat masing-masing tidur abadi anggota keluarga Aubert. Lalu dia mulai meraplal matra yang dia dapatkan dari ingatan NINE HEAD DRAGON, Rapalan mantra itu membuat Clayza kelelahan dan kekuatan magis nya mulai habis dengan sangat cepat... 
    `,
    story13: `Seketika saat sinar magis menyelimuti mereka, ada keajaiban yang terjadi. Mulai dari Lucas Aubert, Amelia Aubert, Louis Aubert, Adeline Aubert, Auguste Aubert, dan Clara Aubert, satu per satu mereka mulai terbangun dari tidur panjang mereka. Mereka saling memandang dengan kebingugan tetapi hanya amelia yang lagsung memahami kondisi mereka, Amelia Bangun dari posisinya dan berjalan ke arah Clayza walau kakinya yang masih kesusahan untuk berjalan Amalia memaksakan itu hingga dia sampai di depan clayza yang tertuntuk lemas.
    Amelia Mengelus kepala clayza dan berkata “Terima kasih karna sudah berjuang untuk kami, Maaf  kami tidak bisa menjadi kaka yang baik untuk mu, Sekarang kamu boleh istirahat biar kami yang mengurus sisanya” Emosi Clayza pun pecah dan membuatnya menangis, saudaranya yang lain masih di ambang kebingungan dengan apa yang terjadi, karna di ingatan mereka mereka baru saja mengalahkan malgarius, tetapi keadaan sekarang sepertinya tidak membahas tentang itu, Clayza yang masih menangispun akhirnya tertidur, 
    `,
    story14: `Lucas bertanya kepada amelia, “Amelia apa yang sebenarnya terjadi disini, bukankan kita baru saja mengalahkan malgarius” 
    Amelia pun menjawab “Memang benar di ingatan kita kita baru saja mengalahkan malgarius, tetapi tidak dengan ingatan adik bungsu kita, dulu aku pernah mendegar mama bercerita tentang tidur didalam keabadian, dan ketika itu pula mama sedang menceritakannya ke clayza, dan juga aku melihat kalung yang di berikan mama selalu di pakai clayza, dan ketika momen terakhir kita mengalahkan malgarius kegelapan seperti meledak, ketika itu pula aku melihat kalung yang di pakai clayza bersinar, seperti cahaya pelindung, dan di saat itu pula aku sadar bahwa cerita mama dahulu, dan kalung itu sangat berkaitan” 
    Adeline pun menyaut “Jadi maksud mu kita tertidur di dalam kebadian selain clayza”  
    `,
    story15: `Kembalinya Aubert yang tertidur menjadi topik yang ramai.. Dan cerita itu sudh sampai ke kerajaan. Para warga mulai berdatangan menuju kediaman Aubert, tetapi tentunya penjagan di sana sangatlah ketat, 4 Hari berlalu clayza masih belum sadar, Clara yang tidak pernah keluar dari kamar clayza dan bahkah tidak pernah menyentuh makanannya pun, membuat saudaranya yang lain khawatir dan datang ke kamar clayza untuk melihat kondisinya. Auguste yang tiba tiba bericara “Apa membangunkan kita, membuat efeknya berbalik” Louis Dan Clara marah dengan ungkapan itu, Amelia mencoba menenangkan mereka, dan berbicara “Itu tidak mungkin, Dia hanya kelelahan karna untuk membangunkan kita membutuhkan kekuatan yang besar” Beberapa saat kemudian Clayza mulai bangun dari tidurnya dan memandang saudaranya, Clara yang melihat itu lagsung memeluk Clayza. 
    Louis “ Yoo Akhirnya kau bangun dasar tukang tidur”
    Clayza “Siapa yang tukang tidur sebenarnya, hahaha”
    Lucas “Apa kondisimu baik baik saja”
    Clayza “Yaa cukup baik, dan Ada yang ingin ku ceritakan kepada kalian, tentang  mama dan papa, dan tentang pasukan kegelapan yang tersisa”
    Ke 6 Saudaranya “Apa yang terjadi dengan mereka”.
    `,
    story16: `Clayza mulai menceritakan semuanya dari awal perjalananya sampai akhir perjalanannya, Tentu saja dia tidak menceritakan tentang Nine Head Drag. Mereka pun senang mendegar kabar orangtuanya yang masih hidup, tetapi kesenangan itu tidak berlangsung lama, mendegar pasukan kegelapan mencoba membaskan malgarius.
    Clayza “Sudah banyak reruntuhan yang aku jelajahi dan begitu banyak tekateki yang aku temukan, pastinya Malgarius bukanlah akhir dari segalanya”
    Lucas sebagai kepala keluarga aubert sementara, memberikan perintah kepada mereka semua untuk bertambah kuat demi menghadapi bencana yang akan datang.
    `,
    story17: `3 tahun telah berlalu tanda tanda kebangkitan dari kegelapan mulai terlihat, Mereka mendapatkan pesan dari pasukan pengintai, bahwa pasukan kegelapan mulai menyerang berbagai wilayah, dan raja pun memberi perintahkan seluruh pasukanya untuk bertarung di sisi Aubert, Louis yang mengatur strategi penyerangan bicara bahwa kita tidak bisa menghadang mereka semua. Clayza lagsung menjawab “Kita fokus saja pada apa yang ada di depan kita, Kita tidak sendiri menghadapi mereka, Ku yakin teman teman yang ku yang lain juga sudah berada di posisi mereka”. `,
    story18: `Perang pun akhirnya di mulai, Korban demi korban terus berjatuhan, Tetapi tidak sedikitpun  mengoyahkan semangat mereka untuk melawan kegelapan, Hingga pada akhirnya para aubert bertemu dengan raja kegelapan sekarang yang memimpin pasukan kegelapan menyerang manusia, Clayza yang saat itu lebih kuat dari kakanya menyadari bahwa bahwa ada keanehan dia takut akan membuat kesalahan yang sama kembali, 
    Clayza “Kak, ada yang aneh dengan dia dulu aku tak menyadarinya tapi sekarang aku yakin kalau dia membawa artefak, tapi aku tidak tau apakah itu artefak yang sama seperti yang sebelumnya atau bukan”
    `,
    story19: `Saudarnya yang lain mulai waspada, Tetapi raja kegelapan menyadari bahwa dia sudah ketahuan membawa artefak dan memilih langsung mengunakannya saat itu juga, Artefak itu memiliki efek penyegelan kekuatan terhadap 1 individu, dan yang di pilih adalah Clayza karna dia meyadarinya terlebih dahulu.`,
    story20: `Saudarnya pun mulai melakukan penyerangan dan mengabaikan clayza yang sedang di segel kekuatanya, karna mereka percaya itu bukanlah apa apa baginya, ke 6 aubert bertarung melawan raja kegelapan, 9 Jam telah berlalu, akhirnya clayza terbebas dari kekangan artefak itu, dan mulai bergabung dengan kakanya menyerang raja kegelapan, dan tak butuh waktu lama kekalahan bagi pasukan kegelapan untuk yang ke 2 kalinya, di berbagai penjuru wilayah juga pasukan kegelapan berhasil di kalahkan.`,
    story21: `Season 3 berakhir dengan kemenangan gemilang keluarga Aubert dalam pertarungan melawan kegelapan yang mengancam dunia. Mereka berhasil mengalahkan pengikut Malgarius dan menghentikan rencana jahat untuk membangkitkan kembali Raja Kegelapan. Dunia kembali dalam keseimbangan dan keberanian keluarga Aubert menjadi legenda yang dikenang oleh semua orang.
    Dalam season selanjutnya, keluarga Aubert akan dihadapkan pada tantangan baru yang lebih besar, mengungkap rahasia masa lalu mereka, dan menemukan takdir mereka yang sebenarnya. 
    `,
    story22: `Season 4: The Prophecy Unveiled

    Season keempat dimulai dengan keluarga Aubert yang memilih untuk menjalani petualangan mereka di dunia yang penuh keajaiban. Setelah berhasil mengalahkan kegelapan dalam pertarungan sebelumnya, mereka kembali bertugas menjaga perdamaian dan keadilan di berbagai kerajaan dan negeri.
    `,
    story23: `Namun, saat mereka menjalankan tugas mereka, mereka menemukan petunjuk-petunjuk yang mengarah pada sebuah ramalan kuno yang berbicara tentang takdir keluarga Aubert dan peran mereka dalam menyelamatkan dunia. Ramalan itu menyatakan bahwa dalam waktu dekat, ada kekuatan jahat yang akan mencoba menguasai dunia dan menyebabkan kehancuran yang tak terbayangkan.
    Keluarga Aubert sadar bahwa mereka tidak bisa mengabaikan ramalan ini. Mereka bersama-sama memulai pencarian panjang untuk mengungkap rahasia di balik ramalan tersebut. Dalam perjalanan mereka, mereka berhadapan dengan penghalang-penghalang yang hebat, menghadapi pengkhianatan dari dalam, dan mengungkap kebenaran yang mengejutkan tentang sejarah keluarga mereka.
    `,
    story24: `Dalam perjalanan mereka, mereka juga bertemu dengan individu-individu luar biasa yang membantu mereka menghadapi bahaya dan mengungkap teka-teki yang semakin rumit. Persahabatan baru terjalin, dan keluarga Aubert semakin kuat dalam persatuan mereka.
    Akhirnya, keluarga Aubert menemukan bahwa ramalan tersebut menunjukkan pada saat ini, ketika kekuatan kegelapan kembali bangkit dan mencoba menguasai dunia. Mereka menyadari bahwa mereka adalah "Pembawa Cahaya," kelompok legendaris yang ditakdirkan untuk melawan kegelapan dan membawa kebaikan dan harapan ke dunia. clayza yang teringat dengan ucapan terakakhir dari Nine Head Dragon yang menyingung tetang penghianat kegelapan, berfikir “jadi semua ini berkaitan, jika semuanya berkaitan lalu apa yang ayahanda dan ibunda lakukan.”
    `,
    story25: `Season 5: The Final Confrontation

	Musim kelima adalah puncak petualangan keluarga Aubert, di mana mereka berhadapan langsung dengan dalang di balik kegelapan yang terus berusaha menguasai dunia. Pertempuran terakhir menjadi titik balik antara kebaikan dan kejahatan, dan nasib dunia bergantung pada ke-7 anggota keluarga Aubert.
`,
    story26: `Dalam pertempuran yang sengit dan dramatis, keluarga Aubert menggunakan keahlian dan kekuatan mereka secara maksimal. Setiap anggota keluarga memberikan segalanya, berjuang dengan tekad dan semangat yang tak tergoyahkan. Mereka saling melindungi satu sama lain dan tidak pernah menyerah dalam menghadapi tantangan yang mematikan.
    Namun, dalam momen kritis pertempuran, keluarga Aubert merasakan kekalahan sudah berada di depan mata mereka. Meskipun mereka telah berjuang dengan sepenuh hati, kekuatan kegelapan terus menguat dan mereka mulai kehilangan harapan. Rasa putus asa mulai melanda dan mereka merasa tak berdaya menghadapi musuh yang lebih kuat.
    `,
    story27: `Tiba-tiba, di tengah kehampaan, kedua orang tua Aubert yang telah lama hilang saat sebuah ekspedisi tiba-tiba muncul di medan pertempuran. Kehadiran mereka membangkitkan semangat dan harapan dalam diri anak-anak mereka. Dengan tekad yang baru, keluarga Aubert bersatu kembali dan bersiap untuk pertempuran terakhir.
    Kedua orang tua Aubert juga memiliki kekuatan luar biasa yang telah mereka kembangkan selama kepergian mereka. Kekuatan mereka mempengaruhi seluruh keluarga Aubert, memberikan mereka keberanian dan dorongan baru. Bersama-sama, mereka melawan kegelapan dengan kekuatan yang tak terbayangkan sebelumnya
    `,
    story28: `Dalam pertempuran yang menegangkan, keluarga Aubert menggunakan kemampuan mereka dengan cara yang saling melengkapi. Lucas menggunakan kemampuan mengendalikan elemen api untuk melawan musuh yang mendekat, sementara Amelia mengeluarkan serangan angin yang kuat untuk menghalangi serangan musuh dari udara.
    Louis memanfaatkan keahliannya dalam strategi untuk menciptakan perangkap dan memanipulasi tanah, menghambat pergerakan musuh. Adeline dengan bijak menggunakan kekuatan magisnya untuk mengendalikan air dan membantu melindungi keluarga Aubert.
    `,
    story29: `Auguste menunjukkan kekuatan fisiknya yang luar biasa dengan mengendalikan kekuatan listriknya untuk menyerang musuh secara langsung, sementara Clara menggunakan kemampuan penyembuhan luar biasanya untuk menjaga kesehatan dan energi keluarga Aubert.
    Tetapi yang paling mengejutkan adalah Clayza. Selama pertempuran yang sengit, saat keputusasaan merajalela dan semuanya tampak suram, Clayza merasakan energi yang tumbuh dalam dirinya. Seiring dengan gelapnya malam yang melingkupi medan pertempuran, ia merasakan kekuatan bayangan dan kegelapan yang tak pernah ia sadari sebelumnya.
    `,
    story30: `Penghianat kegelapan yang disebut oleh Nine Head Dragon terbayang di pikiran Clayza. Ia menyadari bahwa kemampuan barunya yang terkait dengan bayangan dan kegelapan adalah sumber kekuatan yang sebelumnya tersembunyi. Gelapnya malam memberinya kebebasan untuk bergerak dan menyelinap di antara musuh tanpa terdeteksi.
    Dengan keberanian yang membara dalam dirinya, Clayza memutuskan untuk menggabungkan kekuatan barunya dengan dengan berbagai kekuatan. Ia menggunakan bayangan dan kegelapan untuk melindungi dan mempertahankan keluarga Aubert.
    `,
    story31: `Setiap gerakannya yang gesit dan setiap serangan yang ia luncurkan dilakukan dengan penuh kecerdikan. Clayza mampu menyelinap melalui bayangan, muncul dan menghilang kembali tanpa disadari oleh musuh. Ia memanfaatkan kegelapan untuk menghalangi serangan musuh dan menciptakan ilusi yang membingungkan. 
    Akhirnya, dalam pertempuran yang menguras semua tenaga, keluarga Aubert berhasil mengalahkan musuh utama mereka. Kekuatan kegelapan terkunci selamanya, dan dunia diselamatkan dari kehancuran yang tak terbayangkan. Keluarga Aubert menjadi pahlawan yang dihormati oleh semua orang, dan kemenangan mereka memberikan harapan dan keberanian bagi umat manusia.
    `,
    story32: `Setelah pertempuran terakhir, keluarga Aubert diberi penghormatan dan pujian yang layak. Mereka diakui sebagai pelindung kebaikan dan keadilan, dan nama mereka menjadi legenda yang melekat dalam sejarah.
    Dalam penutupan cerita, keluarga Aubert kembali ke kediaman mereka, Diiringi oleh penyambutan dari penduduk kerajaan dan raja itu sendiri, pesta perayaan pun di gelar,  di mana mereka melanjutkan kehidupan mereka sebagai pahlawan yang dihormati. Mereka hidup dalam kebahagiaan dan keharmonisan, membagi kisah-kisah petualangan mereka kepada generasi berikutnya.
    Cerita keluarga Aubert menjadi legenda yang diceritakan dari mulut ke mulut, menginspirasi banyak orang untuk melawan kejahatan dan mempertahankan kebaikan. Warisan keluarga Aubert berlanjut, terus menyala sebagai cahaya yang memberikan harapan kepada dunia yang selalu berjuang dengan kegelapan.    
    Dan alasan kenapa kedua orang tua mereka tidak segera kembali karna Isabelle tau akan bencana itu dan memilih untuk menghalangi rencana dari kegelapan. Dengan kekuatan nya dia dapat melihat seluruh pecahan masa depan, dan akhirnya semuanya sesuai rencananya...
    
    TAMAT.....
    
    Note Amelia: Terima kasih sudah membaca di karenakan ini bot pertama clayza yang make cerita fantasy, jadi sebagai pembukaan membawa nama keseluruhan Aubert, dan maaf jika cerita yang aku buat kurang bagus, waktu clayza minta buatin cerita aku bingung mau nulis ceritanya kek gimana, jadi ini yang terpikir oleh ku, btw ceritanya lagsung satset satset 3 hari doang.
    `,
    story33:`Nantikan cerita RPG terbaru yang baru di next update...`
};